services:
    osu.admin.post:
        class: OSU\AdminBundle\Admin\PostAdmin
        arguments: [~, OSU\EntityBundle\Entity\Post, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Новости, label: Post}
