services:
    osu.admin.post:
        class: OSU\AdminBundle\Admin\PostAdmin
        arguments: [~, OSU\EntityBundle\Entity\Post, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: News, label: Post}

    osu.admin.contacts:
        class: OSU\AdminBundle\Admin\ContactsAdmin
        arguments: [~, OSU\EntityBundle\Entity\Contacts, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Contacts, label: Contacts}

    osu_admin.admin.social:
        class: OSU\AdminBundle\Admin\SocialAdmin
        arguments: [~, OSU\EntityBundle\Entity\Social, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Social Links, label: Social}
